on:
  push:
    branches: [main, master]
  pull_request:

name: Check Code Style

jobs:
  check-code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: R code
        uses: rstudio/shiny-workflows/format-r-code@v1
        with:
          check: true
